easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
    type: annotation

easy_admin_security:
    resource: "@EasyAdminBundle/Controller/SecurityController.php"
    type: annotation

easy_admin_registration:
    resource: "@EasyAdminBundle/Controller/RegistrationController.php"
    type: annotation

easy_admin_translation:
    resource: "@EasyAdminBundle/Controller/TranslationController.php"
    type: annotation